package main

import (
	"context"
	"errors"
	"net/http"
	"strconv"
	"time"

	"github.com/gin-gonic/gin"
	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/primitive"
	"go.mongodb.org/mongo-driver/mongo"
)

type APIResponse struct { Success bool `json:"success"`; Message string `json:"message"`; Data any `json:"data,omitempty"` }

type Transaction struct { ID primitive.ObjectID `bson:"_id,omitempty" json:"id"`; Make string `bson:"make" json:"make"`; Model string `bson:"model" json:"model"`; Year int `bson:"year" json:"year"`; Mileage int `bson:"mileage" json:"mileage"`; SalePrice float64 `bson:"salePrice" json:"salePrice"`; SaleDate time.Time `bson:"saleDate" json:"saleDate"`; Location string `bson:"location" json:"location"`; Condition string `bson:"condition" json:"condition"`; FuelType string `bson:"fuelType" json:"fuelType"`; Transmission string `bson:"transmission" json:"transmission"`; Color *string `bson:"color,omitempty" json:"color,omitempty"` }
type CompetitionListing struct { ID primitive.ObjectID `bson:"_id,omitempty" json:"id"`; Make string `bson:"make" json:"make"`; Model string `bson:"model" json:"model"`; Year int `bson:"year" json:"year"`; Mileage int `bson:"mileage" json:"mileage"`; ListingPrice float64 `bson:"listingPrice" json:"listingPrice"`; Source string `bson:"source" json:"source"`; Location string `bson:"location" json:"location"`; Condition string `bson:"condition" json:"condition"`; DaysOnMarket int `bson:"daysOnMarket" json:"daysOnMarket"`; ListingDate time.Time `bson:"listingDate" json:"listingDate"` }
type VehicleCondition struct { ID primitive.ObjectID `bson:"_id,omitempty" json:"id"`; VIN string `bson:"vin" json:"vin"`; Make string `bson:"make" json:"make"`; Model string `bson:"model" json:"model"`; Year int `bson:"year" json:"year"`; Mileage int `bson:"mileage" json:"mileage"`; OverallGrade string `bson:"overallGrade" json:"overallGrade"`; BodyCondition string `bson:"bodyCondition" json:"bodyCondition"`; EngineCondition string `bson:"engineCondition" json:"engineCondition"`; InteriorCondition string `bson:"interiorCondition" json:"interiorCondition"`; TyreCondition string `bson:"tyreCondition" json:"tyreCondition"`; AccidentHistory bool `bson:"accidentHistory" json:"accidentHistory"`; ServiceHistoryAvailable bool `bson:"serviceHistoryAvailable" json:"serviceHistoryAvailable"`; NumberOfOwners int `bson:"numberOfOwners" json:"numberOfOwners"`; ConditionScore float64 `bson:"conditionScore" json:"conditionScore"` }
type DemandTrend struct { ID primitive.ObjectID `bson:"_id,omitempty" json:"id"`; Make string `bson:"make" json:"make"`; Model string `bson:"model" json:"model"`; Year int `bson:"year" json:"year"`; Month int `bson:"month" json:"month"`; DemandIndex float64 `bson:"demandIndex" json:"demandIndex"`; SearchVolume int `bson:"searchVolume" json:"searchVolume"`; AvgDaysToSell int `bson:"avgDaysToSell" json:"avgDaysToSell"`; Region string `bson:"region" json:"region"`; RecordedAt time.Time `bson:"recordedAt" json:"recordedAt"` }
type NewCarPrice struct { ID primitive.ObjectID `bson:"_id,omitempty" json:"id"`; Make string `bson:"make" json:"make"`; Model string `bson:"model" json:"model"`; Year int `bson:"year" json:"year"`; Variant string `bson:"variant" json:"variant"`; ExShowroomPrice float64 `bson:"exShowroomPrice" json:"exShowroomPrice"`; OnRoadPrice float64 `bson:"onRoadPrice" json:"onRoadPrice"`; EffectiveFrom time.Time `bson:"effectiveFrom" json:"effectiveFrom"`; EffectiveTo *time.Time `bson:"effectiveTo,omitempty" json:"effectiveTo,omitempty"` }
type DepreciationData struct { ID primitive.ObjectID `bson:"_id,omitempty" json:"id"`; Make string `bson:"make" json:"make"`; Model string `bson:"model" json:"model"`; AgeYears int `bson:"ageYears" json:"ageYears"`; MileageBand string `bson:"mileageBand" json:"mileageBand"`; DepreciationPercent float64 `bson:"depreciationPercent" json:"depreciationPercent"`; FuelType string `bson:"fuelType" json:"fuelType"` }

type TransactionRequest struct { Make string `json:"make" binding:"required"`; Model string `json:"model" binding:"required"`; Year int `json:"year" binding:"min=1980,max=2026"`; Mileage int `json:"mileage" binding:"min=0"`; SalePrice float64 `json:"salePrice" binding:"gt=0"`; Location string `json:"location" binding:"required"`; Condition string `json:"condition" binding:"required"`; FuelType string `json:"fuelType" binding:"required"`; Transmission string `json:"transmission" binding:"required"`; Color *string `json:"color"` }
type PricePredictionRequest struct { Make string `json:"make" binding:"required"`; Model string `json:"model" binding:"required"`; Year int `json:"year" binding:"min=1980,max=2026"`; Mileage int `json:"mileage" binding:"min=0"`; Condition string `json:"condition" binding:"required"`; Location string `json:"location" binding:"required"`; FuelType string `json:"fuelType" binding:"required"`; Transmission string `json:"transmission" binding:"required"`; VIN *string `json:"vin"` }

type PricePredictionResponse struct { Make string `json:"make"`; Model string `json:"model"`; Year int `json:"year"`; Mileage int `json:"mileage"`; PredictedPrice float64 `json:"predictedPrice"`; PriceRangeLow float64 `json:"priceRangeLow"`; PriceRangeHigh float64 `json:"priceRangeHigh"`; ConfidenceScore float64 `json:"confidenceScore"`; Factors map[string]any `json:"factors"` }

func registerRoutes(r *gin.Engine, app *App) {
	v := r.Group("/api/v1")
	v.POST("/transactions", app.addTransaction); v.POST("/transactions/bulk", app.bulkTransactions); v.GET("/transactions", app.getTransactions); v.GET("/transactions/search", app.searchTransactions); v.GET("/transactions/average-price", app.averageTransactionPrice); v.GET("/transactions/:id", app.getTransaction); v.DELETE("/transactions/:id", app.deleteTransaction)
	v.POST("/competition", app.addCompetition); v.GET("/competition", app.getCompetition); v.GET("/competition/summary", app.competitionSummary); v.GET("/competition/:id", app.getCompetitionByID); v.DELETE("/competition/:id", app.deleteCompetition)
	v.POST("/conditions", app.addCondition); v.GET("/conditions", app.getConditions); v.GET("/conditions/vin/:vin", app.conditionByVIN); v.GET("/conditions/:id", app.conditionByID); v.DELETE("/conditions/:id", app.deleteCondition)
	v.POST("/demand-trends", app.addDemand); v.GET("/demand-trends", app.getDemand); v.GET("/demand-trends/search", app.searchDemand); v.DELETE("/demand-trends/:id", app.deleteDemand)
	v.POST("/new-car-prices", app.addNewCarPrice); v.GET("/new-car-prices", app.getNewCarPrices); v.GET("/new-car-prices/latest", app.latestNewCarPrice); v.DELETE("/new-car-prices/:id", app.deleteNewCarPrice)
	v.POST("/depreciation", app.addDepreciation); v.GET("/depreciation/calculate", app.calculateDepreciation); v.GET("/depreciation", app.getDepreciation); v.DELETE("/depreciation/:id", app.deleteDepreciation)
	v.POST("/predict", app.predict)
}

func respond(c *gin.Context, status int, msg string, data any) { c.JSON(status, APIResponse{true,msg,data}) }
func idFrom(c *gin.Context) (primitive.ObjectID,error) { return primitive.ObjectIDFromHex(c.Param("id")) }
func deleteByID(c *gin.Context, col *mongo.Collection) { id,err:=idFrom(c); if err!=nil { c.JSON(400,APIResponse{false,"Invalid id",nil}); return }; res,err:=col.DeleteOne(context.Background(),bson.M{"_id":id}); if err!=nil { c.JSON(500,APIResponse{false,err.Error(),nil}); return }; if res.DeletedCount==0 { c.JSON(404,APIResponse{false,"Record not found",nil}); return }; respond(c,200,"Record deleted",nil) }
func (a *App) addTransaction(c *gin.Context) { var q TransactionRequest; if c.ShouldBindJSON(&q)!=nil { c.JSON(400,APIResponse{false,"Invalid request",nil});return }; x:=Transaction{Make:q.Make,Model:q.Model,Year:q.Year,Mileage:q.Mileage,SalePrice:q.SalePrice,Location:q.Location,Condition:q.Condition,FuelType:q.FuelType,Transmission:q.Transmission,Color:q.Color,SaleDate:time.Now()}; r,e:=a.db.Collection("transactions").InsertOne(c,x); if e!=nil {c.JSON(500,APIResponse{false,e.Error(),nil});return}; x.ID=r.InsertedID.(primitive.ObjectID); respond(c,201,"Transaction added successfully",x) }
func (a *App) bulkTransactions(c *gin.Context){var qs []TransactionRequest;if c.ShouldBindJSON(&qs)!=nil||len(qs)==0||len(qs)>500{c.JSON(400,APIResponse{false,"Request must contain 1-500 transactions",nil});return};saved:=[]any{};failed:=[]any{};for i,q:=range qs{x:=Transaction{Make:q.Make,Model:q.Model,Year:q.Year,Mileage:q.Mileage,SalePrice:q.SalePrice,Location:q.Location,Condition:q.Condition,FuelType:q.FuelType,Transmission:q.Transmission,Color:q.Color,SaleDate:time.Now()};r,e:=a.db.Collection("transactions").InsertOne(c,x);if e!=nil{failed=append(failed,map[string]any{"index":i,"make":q.Make,"model":q.Model,"reason":e.Error()})}else{x.ID=r.InsertedID.(primitive.ObjectID);saved=append(saved,x)}};status:=201;if len(failed)>0{status=207};respond(c,status,"Bulk complete",map[string]any{"totalRequested":len(qs),"totalSaved":len(saved),"totalFailed":len(failed),"saved":saved,"failed":failed})}
func (a *App) getTransactions(c *gin.Context){cur,e:=a.db.Collection("transactions").Find(c,bson.M{});if e!=nil{c.JSON(500,APIResponse{false,e.Error(),nil});return};var x []Transaction;e=cur.All(c,&x);if e!=nil{c.JSON(500,APIResponse{false,e.Error(),nil});return};respond(c,200,"Transactions fetched",x)}
func (a *App) getTransaction(c *gin.Context){id,e:=idFrom(c);if e!=nil{c.JSON(400,APIResponse{false,"Invalid id",nil});return};var x Transaction;e=a.db.Collection("transactions").FindOne(c,bson.M{"_id":id}).Decode(&x);if errors.Is(e,mongo.ErrNoDocuments){c.JSON(404,APIResponse{false,"Transaction not found",nil});return};if e!=nil{c.JSON(500,APIResponse{false,e.Error(),nil});return};respond(c,200,"Transaction fetched",x)}
func (a *App) searchTransactions(c *gin.Context){var x []Transaction;cur,e:=a.db.Collection("transactions").Find(c,bson.M{"make":c.Query("make"),"model":c.Query("model")});if e==nil{e=cur.All(c,&x)};if e!=nil{c.JSON(500,APIResponse{false,e.Error(),nil});return};respond(c,200,"Transactions fetched",x)}
func (a *App) averageTransactionPrice(c *gin.Context){var x []Transaction; y,_:=strconv.Atoi(c.Query("year"));cur,e:=a.db.Collection("transactions").Find(c,bson.M{"make":c.Query("make"),"model":c.Query("model"),"year":y});if e==nil{e=cur.All(c,&x)};if e!=nil{c.JSON(500,APIResponse{false,e.Error(),nil});return};var sum float64;for _,v:=range x{sum+=v.SalePrice};avg:=0.0;if len(x)>0{avg=sum/float64(len(x))};respond(c,200,"Average price computed",avg)}
func (a *App) deleteTransaction(c *gin.Context){deleteByID(c,a.db.Collection("transactions"))}

func (a *App) addCompetition(c *gin.Context){var x CompetitionListing;if c.ShouldBindJSON(&x)!=nil{c.JSON(400,APIResponse{false,"Invalid request",nil});return};x.ListingDate=time.Now();r,e:=a.db.Collection("competition_listings").InsertOne(c,x);if e!=nil{c.JSON(500,APIResponse{false,e.Error(),nil});return};x.ID=r.InsertedID.(primitive.ObjectID);respond(c,201,"Listing added",x)}
func (a *App) getCompetition(c *gin.Context){var x []CompetitionListing;cur,e:=a.db.Collection("competition_listings").Find(c,bson.M{});if e==nil{e=cur.All(c,&x)};if e!=nil{c.JSON(500,APIResponse{false,e.Error(),nil});return};respond(c,200,"Listings fetched",x)}
func (a *App) getCompetitionByID(c *gin.Context){id,e:=idFrom(c);var x CompetitionListing;if e==nil{e=a.db.Collection("competition_listings").FindOne(c,bson.M{"_id":id}).Decode(&x)};if e!=nil{c.JSON(404,APIResponse{false,"Listing not found",nil});return};respond(c,200,"Listing fetched",x)}
func (a *App) competitionSummary(c *gin.Context){y,_:=strconv.Atoi(c.Query("year"));var x []CompetitionListing;cur,e:=a.db.Collection("competition_listings").Find(c,bson.M{"make":c.Query("make"),"model":c.Query("model"),"year":y});if e==nil{e=cur.All(c,&x)};if e!=nil{c.JSON(500,APIResponse{false,e.Error(),nil});return};var sum,min,max,days float64;for i,v:=range x{sum+=v.ListingPrice;days+=float64(v.DaysOnMarket);if i==0||v.ListingPrice<min{min=v.ListingPrice};if v.ListingPrice>max{max=v.ListingPrice}};avg:=0.0;ad:=0.0;if len(x)>0{avg=sum/float64(len(x));ad=days/float64(len(x))};respond(c,200,"Summary fetched",map[string]any{"make":c.Query("make"),"model":c.Query("model"),"year":y,"averageListingPrice":avg,"minPrice":min,"maxPrice":max,"totalListings":len(x),"avgDaysOnMarket":ad})}
func (a *App) deleteCompetition(c *gin.Context){deleteByID(c,a.db.Collection("competition_listings"))}

func (a *App) addCondition(c *gin.Context){var x VehicleCondition;if c.ShouldBindJSON(&x)!=nil{c.JSON(400,APIResponse{false,"Invalid request",nil});return};r,e:=a.db.Collection("vehicle_conditions").InsertOne(c,x);if e!=nil{c.JSON(500,APIResponse{false,e.Error(),nil});return};x.ID=r.InsertedID.(primitive.ObjectID);respond(c,201,"Condition added",x)}
func (a *App) getConditions(c *gin.Context){var x []VehicleCondition;cur,e:=a.db.Collection("vehicle_conditions").Find(c,bson.M{});if e==nil{e=cur.All(c,&x)};if e!=nil{c.JSON(500,APIResponse{false,e.Error(),nil});return};respond(c,200,"Records fetched",x)}
func (a *App) conditionByVIN(c *gin.Context){var x VehicleCondition;e:=a.db.Collection("vehicle_conditions").FindOne(c,bson.M{"vin":c.Param("vin")}).Decode(&x);if e!=nil{c.JSON(404,APIResponse{false,"Vehicle condition not found",nil});return};respond(c,200,"Record fetched",x)}
func (a *App) conditionByID(c *gin.Context){id,e:=idFrom(c);var x VehicleCondition;if e==nil{e=a.db.Collection("vehicle_conditions").FindOne(c,bson.M{"_id":id}).Decode(&x)};if e!=nil{c.JSON(404,APIResponse{false,"Record not found",nil});return};respond(c,200,"Record fetched",x)}
func (a *App) deleteCondition(c *gin.Context){deleteByID(c,a.db.Collection("vehicle_conditions"))}

func (a *App) addDemand(c *gin.Context){var x DemandTrend;if c.ShouldBindJSON(&x)!=nil{c.JSON(400,APIResponse{false,"Invalid request",nil});return};x.RecordedAt=time.Now();r,e:=a.db.Collection("demand_trends").InsertOne(c,x);if e!=nil{c.JSON(500,APIResponse{false,e.Error(),nil});return};x.ID=r.InsertedID.(primitive.ObjectID);respond(c,201,"Trend added",x)}
func (a *App) getDemand(c *gin.Context){var x []DemandTrend;cur,e:=a.db.Collection("demand_trends").Find(c,bson.M{});if e==nil{e=cur.All(c,&x)};if e!=nil{c.JSON(500,APIResponse{false,e.Error(),nil});return};respond(c,200,"Trends fetched",x)}
func (a *App) searchDemand(c *gin.Context){var x []DemandTrend;cur,e:=a.db.Collection("demand_trends").Find(c,bson.M{"make":c.Query("make"),"model":c.Query("model")});if e==nil{e=cur.All(c,&x)};if e!=nil{c.JSON(500,APIResponse{false,e.Error(),nil});return};respond(c,200,"Trends fetched",x)}
func (a *App) deleteDemand(c *gin.Context){deleteByID(c,a.db.Collection("demand_trends"))}

func (a *App) addNewCarPrice(c *gin.Context){var x NewCarPrice;if c.ShouldBindJSON(&x)!=nil{c.JSON(400,APIResponse{false,"Invalid request",nil});return};if x.EffectiveFrom.IsZero(){x.EffectiveFrom=time.Now()};r,e:=a.db.Collection("new_car_prices").InsertOne(c,x);if e!=nil{c.JSON(500,APIResponse{false,e.Error(),nil});return};x.ID=r.InsertedID.(primitive.ObjectID);respond(c,201,"Price added",x)}
func (a *App) getNewCarPrices(c *gin.Context){var x []NewCarPrice;cur,e:=a.db.Collection("new_car_prices").Find(c,bson.M{});if e==nil{e=cur.All(c,&x)};if e!=nil{c.JSON(500,APIResponse{false,e.Error(),nil});return};respond(c,200,"Prices fetched",x)}
func (a *App) latestNewCarPrice(c *gin.Context){y,_:=strconv.Atoi(c.Query("year"));var x []NewCarPrice;cur,e:=a.db.Collection("new_car_prices").Find(c,bson.M{"make":c.Query("make"),"model":c.Query("model"),"year":y});if e==nil{e=cur.All(c,&x)};if e!=nil{c.JSON(500,APIResponse{false,e.Error(),nil});return};var best *NewCarPrice;for i:=range x{if best==nil||x[i].EffectiveFrom.After(best.EffectiveFrom){best=&x[i]}};price:=0.0;if best!=nil{price=best.OnRoadPrice};respond(c,200,"Latest price fetched",price)}
func (a *App) deleteNewCarPrice(c *gin.Context){deleteByID(c,a.db.Collection("new_car_prices"))}

func (a *App) addDepreciation(c *gin.Context){var x DepreciationData;if c.ShouldBindJSON(&x)!=nil{c.JSON(400,APIResponse{false,"Invalid request",nil});return};r,e:=a.db.Collection("depreciation_data").InsertOne(c,x);if e!=nil{c.JSON(500,APIResponse{false,e.Error(),nil});return};x.ID=r.InsertedID.(primitive.ObjectID);respond(c,201,"Depreciation added",x)}
func (a *App) getDepreciation(c *gin.Context){var x []DepreciationData;cur,e:=a.db.Collection("depreciation_data").Find(c,bson.M{});if e==nil{e=cur.All(c,&x)};if e!=nil{c.JSON(500,APIResponse{false,e.Error(),nil});return};respond(c,200,"Records fetched",x)}
func (a *App) calculateDepreciation(c *gin.Context){age,_:=strconv.Atoi(c.Query("ageYears"));filter:=bson.M{"make":c.Query("make"),"model":c.Query("model"),"ageYears":age,"fuelType":c.Query("fuelType")};var x DepreciationData;e:=a.db.Collection("depreciation_data").FindOne(c,filter).Decode(&x);if e==mongo.ErrNoDocuments{filter=bson.M{"make":c.Query("make"),"model":c.Query("model"),"ageYears":age};e=a.db.Collection("depreciation_data").FindOne(c,filter).Decode(&x)};pct:=x.DepreciationPercent;if e!=nil{switch{case age<=1:pct=15;case age<=3:pct=30;case age<=5:pct=45;case age<=8:pct=60;default:pct=70}};respond(c,200,"Depreciation calculated",pct)}
func (a *App) deleteDepreciation(c *gin.Context){deleteByID(c,a.db.Collection("depreciation_data"))}

func (a *App) predict(c *gin.Context){var q PricePredictionRequest;if c.ShouldBindJSON(&q)!=nil{c.JSON(400,APIResponse{false,"Invalid request",nil});return};ctx:=c; y:=q.Year;var txns []Transaction;cur,_:=a.db.Collection("transactions").Find(ctx,bson.M{"make":q.Make,"model":q.Model,"year":y});if cur!=nil{_ = cur.All(ctx,&txns)};var avgTxn float64;for _,x:=range txns{avgTxn+=x.SalePrice};if len(txns)>0{avgTxn/=float64(len(txns))};var listings []CompetitionListing;cur,_=a.db.Collection("competition_listings").Find(ctx,bson.M{"make":q.Make,"model":q.Model,"year":y});if cur!=nil{_ = cur.All(ctx,&listings)};var avgComp float64;for _,x:=range listings{avgComp+=x.ListingPrice};if len(listings)>0{avgComp/=float64(len(listings))};age:=time.Now().Year()-y;pct:=defaultDep(age);var dep DepreciationData;e:=a.db.Collection("depreciation_data").FindOne(ctx,bson.M{"make":q.Make,"model":q.Model,"ageYears":age,"fuelType":q.FuelType}).Decode(&dep);if e==nil{pct=dep.DepreciationPercent};var nc []NewCarPrice;cur,_=a.db.Collection("new_car_prices").Find(ctx,bson.M{"make":q.Make,"model":q.Model,"year":y});if cur!=nil{_ = cur.All(ctx,&nc)};var newPrice float64;for _,x:=range nc{if x.OnRoadPrice>newPrice{newPrice=x.OnRoadPrice}};price:=0.0;if avgTxn>0{price+=avgTxn*.4};if avgComp>0{price+=avgComp*.3};if newPrice>0{price+=newPrice*(1-pct/100)*.2};if q.VIN!=nil{var vc VehicleCondition;if a.db.Collection("vehicle_conditions").FindOne(ctx,bson.M{"vin":*q.VIN}).Decode(&vc)==nil{price*=.85+(vc.ConditionScore/10)*.30}};confidence:=10.0;if avgTxn>0{confidence+=40};if len(listings)>0{confidence+=30};f:=map[string]any{"avgTransactionPrice":avgTxn,"avgCompetitionPrice":avgComp,"newCarOnRoadPrice":newPrice,"depreciationPercent":pct,"computedAt":time.Now()};result:=PricePredictionResponse{q.Make,q.Model,q.Year,q.Mileage,price,price*.9,price*1.1,confidence,f};respond(c,200,"Price predicted successfully",result)}
func defaultDep(age int)float64{switch{case age<=1:return 15;case age<=3:return 30;case age<=5:return 45;case age<=8:return 60;default:return 70}}
